apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: carts-api
spec:
  interval: 1m
  dependsOn:
  - name: global-config
  sourceRef:
    kind: GitRepository
    name: flux-specs-apps
  path: "./apps/carts-api/overlays/dev"
  prune: true
  timeout: 1m
